---
- hosts: sql
  remote_user: ec2-user
  become: yes
  become_method: sudo
  tasks:
    - name: Install Apache, MySQL, and PHP5
      yum: name={{ item }} state=present
      with_items:
        - httpd
        - https://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm
        - mysql-community-server
        - python
        - php
        - php-pear
        - php-mysql

    - name: Turn on Apache and MySQL and set them to run on boot
      service: name={{ item }} state=started enabled=yes
      with_items:
        - httpd
        - mysqld

    - name: Create a test database
      mysql_db: name=testDb
                state=present

    - name: Create a new user for connections
      mysql_user: name=webapp
                  password=mypassword
                  priv=*.*:ALL state=present
