---
- hosts: webservers
  remote_user: ec2-user
  become: yes
  become_method: sudo
  tasks:
    - name: install apache
      yum:
        name: httpd
        state: latest   
    - name: start the apache and enable
      service:
        name: httpd
        state: started
        enabled: yes
    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart httpd

  handlers:
    - name: restart httpd
      service: name=httpd state=restarted

