---
- hosts: webservers
  remote_user: ec2-user
  become: yes
  become_method: sudo
  tasks:
    - name: Copy the nginx repo to servers
      service: name=nginx state=started
    - name: disable selinux
      command: /sbin/setenforce 0
  
    
