---
- hosts: webservers
  remote_user: ec2-user
  become: yes
  become_method: sudo
  vars: 
   - MyMessage: "Welomce to ansible world!"
  tasks:
   - name: Nginx setup
     yum:
       name: amazon-linux-extras nginx1.12
       state: installed 
       update_cache: true
   - name: index.html copy
     template: 
       src: index.html.j2 
       dest: /usr/nginx/html/index.html

